# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RPCMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RPCMessage.proto',
  package='',
  serialized_pb='\n\x10RPCMessage.proto\"@\n\nRPCRequest\x12\x0e\n\x06\x63\x61llid\x18\x01 \x02(\x05\x12\x12\n\nmethodName\x18\x02 \x02(\t\x12\x0e\n\x06params\x18\x03 \x02(\x0c\"/\n\x0bRPCResponse\x12\x0e\n\x06\x63\x61llid\x18\x01 \x02(\x05\x12\x10\n\x08retvalue\x18\x02 \x02(\x0c')




_RPCREQUEST = _descriptor.Descriptor(
  name='RPCRequest',
  full_name='RPCRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='callid', full_name='RPCRequest.callid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='methodName', full_name='RPCRequest.methodName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='params', full_name='RPCRequest.params', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=84,
)


_RPCRESPONSE = _descriptor.Descriptor(
  name='RPCResponse',
  full_name='RPCResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='callid', full_name='RPCResponse.callid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='retvalue', full_name='RPCResponse.retvalue', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=86,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['RPCRequest'] = _RPCREQUEST
DESCRIPTOR.message_types_by_name['RPCResponse'] = _RPCRESPONSE

class RPCRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RPCREQUEST

  # @@protoc_insertion_point(class_scope:RPCRequest)

class RPCResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RPCRESPONSE

  # @@protoc_insertion_point(class_scope:RPCResponse)


# @@protoc_insertion_point(module_scope)
