// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RPCMessage.proto

#ifndef PROTOBUF_RPCMessage_2eproto__INCLUDED
#define PROTOBUF_RPCMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_RPCMessage_2eproto();
void protobuf_AssignDesc_RPCMessage_2eproto();
void protobuf_ShutdownFile_RPCMessage_2eproto();

class RPCRequest_pb2;
class RPCResponse_pb2;

// ===================================================================

class RPCRequest_pb2 : public ::google::protobuf::Message {
 public:
  RPCRequest_pb2();
  virtual ~RPCRequest_pb2();

  RPCRequest_pb2(const RPCRequest_pb2& from);

  inline RPCRequest_pb2& operator=(const RPCRequest_pb2& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RPCRequest_pb2& default_instance();

  void Swap(RPCRequest_pb2* other);

  // implements Message ----------------------------------------------

  RPCRequest_pb2* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RPCRequest_pb2& from);
  void MergeFrom(const RPCRequest_pb2& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 callid = 1;
  inline bool has_callid() const;
  inline void clear_callid();
  static const int kCallidFieldNumber = 1;
  inline ::google::protobuf::int32 callid() const;
  inline void set_callid(::google::protobuf::int32 value);

  // required string methodName = 2;
  inline bool has_methodname() const;
  inline void clear_methodname();
  static const int kMethodNameFieldNumber = 2;
  inline const ::std::string& methodname() const;
  inline void set_methodname(const ::std::string& value);
  inline void set_methodname(const char* value);
  inline void set_methodname(const char* value, size_t size);
  inline ::std::string* mutable_methodname();
  inline ::std::string* release_methodname();
  inline void set_allocated_methodname(::std::string* methodname);

  // required bytes params = 3;
  inline bool has_params() const;
  inline void clear_params();
  static const int kParamsFieldNumber = 3;
  inline const ::std::string& params() const;
  inline void set_params(const ::std::string& value);
  inline void set_params(const char* value);
  inline void set_params(const void* value, size_t size);
  inline ::std::string* mutable_params();
  inline ::std::string* release_params();
  inline void set_allocated_params(::std::string* params);

  // @@protoc_insertion_point(class_scope:RPCRequest_pb2)
 private:
  inline void set_has_callid();
  inline void clear_has_callid();
  inline void set_has_methodname();
  inline void clear_has_methodname();
  inline void set_has_params();
  inline void clear_has_params();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* methodname_;
  ::std::string* params_;
  ::google::protobuf::int32 callid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_RPCMessage_2eproto();
  friend void protobuf_AssignDesc_RPCMessage_2eproto();
  friend void protobuf_ShutdownFile_RPCMessage_2eproto();

  void InitAsDefaultInstance();
  static RPCRequest_pb2* default_instance_;
};
// -------------------------------------------------------------------

class RPCResponse_pb2 : public ::google::protobuf::Message {
 public:
  RPCResponse_pb2();
  virtual ~RPCResponse_pb2();

  RPCResponse_pb2(const RPCResponse_pb2& from);

  inline RPCResponse_pb2& operator=(const RPCResponse_pb2& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RPCResponse_pb2& default_instance();

  void Swap(RPCResponse_pb2* other);

  // implements Message ----------------------------------------------

  RPCResponse_pb2* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RPCResponse_pb2& from);
  void MergeFrom(const RPCResponse_pb2& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 callid = 1;
  inline bool has_callid() const;
  inline void clear_callid();
  static const int kCallidFieldNumber = 1;
  inline ::google::protobuf::int32 callid() const;
  inline void set_callid(::google::protobuf::int32 value);

  // required bytes retvalue = 2;
  inline bool has_retvalue() const;
  inline void clear_retvalue();
  static const int kRetvalueFieldNumber = 2;
  inline const ::std::string& retvalue() const;
  inline void set_retvalue(const ::std::string& value);
  inline void set_retvalue(const char* value);
  inline void set_retvalue(const void* value, size_t size);
  inline ::std::string* mutable_retvalue();
  inline ::std::string* release_retvalue();
  inline void set_allocated_retvalue(::std::string* retvalue);

  // @@protoc_insertion_point(class_scope:RPCResponse_pb2)
 private:
  inline void set_has_callid();
  inline void clear_has_callid();
  inline void set_has_retvalue();
  inline void clear_has_retvalue();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* retvalue_;
  ::google::protobuf::int32 callid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_RPCMessage_2eproto();
  friend void protobuf_AssignDesc_RPCMessage_2eproto();
  friend void protobuf_ShutdownFile_RPCMessage_2eproto();

  void InitAsDefaultInstance();
  static RPCResponse_pb2* default_instance_;
};
// ===================================================================


// ===================================================================

// RPCRequest_pb2

// required int32 callid = 1;
inline bool RPCRequest_pb2::has_callid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RPCRequest_pb2::set_has_callid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RPCRequest_pb2::clear_has_callid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RPCRequest_pb2::clear_callid() {
  callid_ = 0;
  clear_has_callid();
}
inline ::google::protobuf::int32 RPCRequest_pb2::callid() const {
  return callid_;
}
inline void RPCRequest_pb2::set_callid(::google::protobuf::int32 value) {
  set_has_callid();
  callid_ = value;
}

// required string methodName = 2;
inline bool RPCRequest_pb2::has_methodname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RPCRequest_pb2::set_has_methodname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RPCRequest_pb2::clear_has_methodname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RPCRequest_pb2::clear_methodname() {
  if (methodname_ != &::google::protobuf::internal::kEmptyString) {
    methodname_->clear();
  }
  clear_has_methodname();
}
inline const ::std::string& RPCRequest_pb2::methodname() const {
  return *methodname_;
}
inline void RPCRequest_pb2::set_methodname(const ::std::string& value) {
  set_has_methodname();
  if (methodname_ == &::google::protobuf::internal::kEmptyString) {
    methodname_ = new ::std::string;
  }
  methodname_->assign(value);
}
inline void RPCRequest_pb2::set_methodname(const char* value) {
  set_has_methodname();
  if (methodname_ == &::google::protobuf::internal::kEmptyString) {
    methodname_ = new ::std::string;
  }
  methodname_->assign(value);
}
inline void RPCRequest_pb2::set_methodname(const char* value, size_t size) {
  set_has_methodname();
  if (methodname_ == &::google::protobuf::internal::kEmptyString) {
    methodname_ = new ::std::string;
  }
  methodname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RPCRequest_pb2::mutable_methodname() {
  set_has_methodname();
  if (methodname_ == &::google::protobuf::internal::kEmptyString) {
    methodname_ = new ::std::string;
  }
  return methodname_;
}
inline ::std::string* RPCRequest_pb2::release_methodname() {
  clear_has_methodname();
  if (methodname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = methodname_;
    methodname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void RPCRequest_pb2::set_allocated_methodname(::std::string* methodname) {
  if (methodname_ != &::google::protobuf::internal::kEmptyString) {
    delete methodname_;
  }
  if (methodname) {
    set_has_methodname();
    methodname_ = methodname;
  } else {
    clear_has_methodname();
    methodname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required bytes params = 3;
inline bool RPCRequest_pb2::has_params() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RPCRequest_pb2::set_has_params() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RPCRequest_pb2::clear_has_params() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RPCRequest_pb2::clear_params() {
  if (params_ != &::google::protobuf::internal::kEmptyString) {
    params_->clear();
  }
  clear_has_params();
}
inline const ::std::string& RPCRequest_pb2::params() const {
  return *params_;
}
inline void RPCRequest_pb2::set_params(const ::std::string& value) {
  set_has_params();
  if (params_ == &::google::protobuf::internal::kEmptyString) {
    params_ = new ::std::string;
  }
  params_->assign(value);
}
inline void RPCRequest_pb2::set_params(const char* value) {
  set_has_params();
  if (params_ == &::google::protobuf::internal::kEmptyString) {
    params_ = new ::std::string;
  }
  params_->assign(value);
}
inline void RPCRequest_pb2::set_params(const void* value, size_t size) {
  set_has_params();
  if (params_ == &::google::protobuf::internal::kEmptyString) {
    params_ = new ::std::string;
  }
  params_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RPCRequest_pb2::mutable_params() {
  set_has_params();
  if (params_ == &::google::protobuf::internal::kEmptyString) {
    params_ = new ::std::string;
  }
  return params_;
}
inline ::std::string* RPCRequest_pb2::release_params() {
  clear_has_params();
  if (params_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = params_;
    params_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void RPCRequest_pb2::set_allocated_params(::std::string* params) {
  if (params_ != &::google::protobuf::internal::kEmptyString) {
    delete params_;
  }
  if (params) {
    set_has_params();
    params_ = params;
  } else {
    clear_has_params();
    params_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// RPCResponse_pb2

// required int32 callid = 1;
inline bool RPCResponse_pb2::has_callid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RPCResponse_pb2::set_has_callid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RPCResponse_pb2::clear_has_callid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RPCResponse_pb2::clear_callid() {
  callid_ = 0;
  clear_has_callid();
}
inline ::google::protobuf::int32 RPCResponse_pb2::callid() const {
  return callid_;
}
inline void RPCResponse_pb2::set_callid(::google::protobuf::int32 value) {
  set_has_callid();
  callid_ = value;
}

// required bytes retvalue = 2;
inline bool RPCResponse_pb2::has_retvalue() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RPCResponse_pb2::set_has_retvalue() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RPCResponse_pb2::clear_has_retvalue() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RPCResponse_pb2::clear_retvalue() {
  if (retvalue_ != &::google::protobuf::internal::kEmptyString) {
    retvalue_->clear();
  }
  clear_has_retvalue();
}
inline const ::std::string& RPCResponse_pb2::retvalue() const {
  return *retvalue_;
}
inline void RPCResponse_pb2::set_retvalue(const ::std::string& value) {
  set_has_retvalue();
  if (retvalue_ == &::google::protobuf::internal::kEmptyString) {
    retvalue_ = new ::std::string;
  }
  retvalue_->assign(value);
}
inline void RPCResponse_pb2::set_retvalue(const char* value) {
  set_has_retvalue();
  if (retvalue_ == &::google::protobuf::internal::kEmptyString) {
    retvalue_ = new ::std::string;
  }
  retvalue_->assign(value);
}
inline void RPCResponse_pb2::set_retvalue(const void* value, size_t size) {
  set_has_retvalue();
  if (retvalue_ == &::google::protobuf::internal::kEmptyString) {
    retvalue_ = new ::std::string;
  }
  retvalue_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RPCResponse_pb2::mutable_retvalue() {
  set_has_retvalue();
  if (retvalue_ == &::google::protobuf::internal::kEmptyString) {
    retvalue_ = new ::std::string;
  }
  return retvalue_;
}
inline ::std::string* RPCResponse_pb2::release_retvalue() {
  clear_has_retvalue();
  if (retvalue_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = retvalue_;
    retvalue_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void RPCResponse_pb2::set_allocated_retvalue(::std::string* retvalue) {
  if (retvalue_ != &::google::protobuf::internal::kEmptyString) {
    delete retvalue_;
  }
  if (retvalue) {
    set_has_retvalue();
    retvalue_ = retvalue;
  } else {
    clear_has_retvalue();
    retvalue_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_RPCMessage_2eproto__INCLUDED
